env:
  TERM: xterm-256color

font:
  normal:
    family: ShureTechMono Nerd Font
    style: Regular

  bold:
    family: ShureTechMono Nerd Font
    style: Bold

  italic:
    family: ShureTechMono Nerd Font
    style: Italic

  bold_italic:
    family: ShureTechMono Nerd Font
    style: Bold Italic

  size: 14

window:
  title: Terminal
  dynamic_title: true
  dimensions:
    columns: 160
    lines: 48
  padding:
    x: 5
    y: 5

scrolling:
  history: 9999

draw_bold_text_with_bright_colors: true

dpi:
  x: 96.0
  y: 96.0

cursor:
  style: 
    shape: Block
    blinking: Always
  blink_interval: 333
  unfocused_hollow: true

live_config_reload: true

colors:
  # COLORSCHEME: base16-spacemacs-256.yml modified
  # Default colors
  primary:
    background: '0x1f2022'
    foreground: '0xa3a3a3'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1f2022'
    cursor: '0xe8a317'

  # Normal colors
  normal:
    black: '0x1f2022'
    red: '0xf2241f'
    green: '0x67b11d'
    yellow: '0xb1951d'
    blue: '0x4f97d7'
    magenta: '0xa31db1'
    cyan: '0x2d9574'
    white: '0xa3a3a3'

  # Bright colors
  bright:
    black: '0x585858'
    red: '0xf2241f'
    green: '0x67b11d'
    yellow: '0xb1951d'
    blue: '0x4f97d7'
    magenta: '0xa31db1'
    cyan: '0x2d9574'
    white: '0xf8f8f8'

  indexed_colors:
    - {index: 16, color: '0xffa500'}
    - {index: 17, color: '0xb03060'}
    - {index: 18, color: '0x282828'}
    - {index: 19, color: '0x444155'}
    - {index: 20, color: '0xb8b8b8'}
    - {index: 21, color: '0xe8e8e8'}
