env:
  TERM: xterm-256color

font:
  normal:
    family: ShureTechMono Nerd Font
    style: Regular

  bold:
    family: ShureTechMono Nerd Font
    style: Bold

  italic:
    family: ShureTechMono Nerd Font
    style: Italic

  bold_italic:
    family: ShureTechMono Nerd Font
    style: Bold Italic

  size: 14

window:
  title: Terminal
  dynamic_title: true
  dimensions:
    columns: 160
    lines: 48
  padding:
    x: 5
    y: 5

scrolling:
  history: 9999

draw_bold_text_with_bright_colors: true

dpi:
  x: 96.0
  y: 96.0

cursor:
  style: 
    shape: Block
    blinking: Always
  blink_interval: 333
  unfocused_hollow: true

live_config_reload: true

colors:
  primary:
    background: "#0D0D0D"
    foreground: "#F5F5F5"
    dim_foreground: "#DCDCDC"
  cursor:
    text: "#333333"
    cursor: "#FF7F50"
  vi_mode_cursor:
    text: "#333333"
    cursor: "#FF7F50"
  selection:
    text: CellForeground
    background: "#483d8b"
  search:
    matches:
      foreground: "#F5F5F5"
      background: "#333333"
    footer_bar:
      background: "#3B4252"
      foreground: "#d8dee9"
  normal:
    black: "#0D0D0D"
    red: "#B22222"
    green: "#00CD66"
    yellow: "#CDBE70"
    blue: "#7AC5CD"
    magenta: "#CD96CD"
    cyan: "#00C5CD"
    white: "#DCDCDC"
  bright:
    black: "#333333"
    red: "#FF7F50"
    green: "#00FF7F"
    yellow: "#FFEC8B"
    blue: "#98F5FF"
    magenta: "#FFBBFF"
    cyan: "#00F5FF"
    white: "#F5F5F5"
  dim:
    black: "#0D0D0D"
    red: "#B22222"
    green: "#00CD66"
    yellow: "#CDBE70"
    blue: "#7AC5CD"
    magenta: "#CD96CD"
    cyan: "#00C5CD"
    white: "#DCDCDC"

key_bindings:
  - { key: V,        mods: Control|Shift, action: Paste                 }
  - { key: C,        mods: Control|Shift, action: Copy                  }
  - { key: Q,        mods: Control|Shift, action: Quit                  }
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance      }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt }
