[general]
live_config_reload = true

[terminal]
shell = { program = "bash", args = ["-l"] }

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#091310"
foreground = "#B7E3D8"
dim_foreground = "#8AA39B"
bright_foreground = "#E0F5EF"

[colors.bright]
black = "#40514C"
red = "#F06D75"
green = "#8BDFC4"
yellow = "#FFD166"
blue = "#80B9E8"
magenta = "#B89CE8"
cyan = "#8AE1E7"
white = "#E0F5EF"

[colors.normal]
black = "#091310"
red = "#CE2029"
green = "#6FC7B0"
yellow = "#F5A500"
blue = "#568CC5"
magenta = "#AB80C4"
cyan = "#65BFC4"
white = "#B7E3D8"

[colors.dim]
black = "#091310"
red = "#8F292F"
green = "#4F9381"
yellow = "#B87D16"
blue = "#416B95"
magenta = "#806395"
cyan = "#4C9093"
white = "#829F97"

[colors.cursor]
text = "#091310"
cursor = "#FF7900"

[colors.selection]
background = "#333333"
foreground = "#F5F5F5"

[colors.search.matches]
background = "#333333"
foreground = "#F5F5F5"

[colors.search.focused_match]
background = "#111111"
foreground = "#eeeeee"

[cursor]
style = {
  shape = "Block",
  blinking = "Always"
}
blink_interval = 333
blink_timeout = 0
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 11
normal = {
  family = "EnvyCodeR Nerd Font Mono",
  style = "Regular"
}

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Q",        mods = "Control|Shift", action = "Quit" },
  { key = "Return",   mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "+",        mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "_",        mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = ")",        mods = "Control|Shift", action = "ResetFontSize" },
  { key = "PageUp",   mods = "Shift", mode = "~Alt", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ScrollPageDown" },
  { key = "Home",     mods = "Shift", mode = "~Alt", action = "ScrollToTop" },
  { key = "End",      mods = "Shift", mode = "~Alt", action = "ScrollToBottom" },
]

[scrolling]
history = 9999
multiplier = 5

[selection]
save_to_clipboard = true

[window]
padding = { x = 5, y = 5 }
dimensions = { columns = 160, lines = 48 }
dynamic_title = true
title = "Terminal"
